### ISSUE TITLE
Login should return boolean true or false instead the nurse object data

### ISSUE THREAD

**Issue by Japoivvb** [Xavier-Amatller/exempleProjecte#10]
https://github.com/Xavier-Amatller/exempleProjecte/blob/eefa145d9d6b91cd93d10a37b305d31b40d76b99/src/Controller/NurseController.php#L59

**Comment by HodeonArtz** [comment]
Login already returns a `boolean` true or false
https://github.com/Xavier-Amatller/exempleProjecte/blob/eefa145d9d6b91cd93d10a37b305d31b40d76b99/src/Controller/NurseController.php#L54-L60
in_array() returns a boolean
