### ISSUE TITLE
Include technical email validation

### ISSUE THREAD

**Issue by Japoivvb** [Xavier-Amatller/exempleProjecte#51]
https://github.com/Xavier-Amatller/exempleProjecte/blob/0a6eb4f8c940e1734e33b06ce71e3d2d25274087/src/Controller/NurseController.php#L35

guide
https://www.w3schools.com/php/php_form_url_email.asp

**Comment by HodeonArtz** [comment]
Email validation on lines:
https://github.com/Xavier-Amatller/exempleProjecte/blob/0a6eb4f8c940e1734e33b06ce71e3d2d25274087/src/Controller/NurseController.php#L34

https://github.com/Xavier-Amatller/exempleProjecte/blob/0a6eb4f8c940e1734e33b06ce71e3d2d25274087/src/Controller/NurseController.php#L187
