### ISSUE TITLE
Use HTTP codes constant error already defined

### ISSUE THREAD

**Issue by Japoivvb** [Xavier-Amatller/exempleProjecte#52]
https://github.com/Xavier-Amatller/exempleProjecte/blob/0a6eb4f8c940e1734e33b06ce71e3d2d25274087/src/Controller/NurseController.php#L53

defined in  Symfony\Component\HttpFoundation\Response
	e.g. public const HTTP_OK = 200;

**Comment by Xavier-Amatller** [comment]
![image](https://github.com/user-attachments/assets/087c1eeb-0409-4ff7-80bc-477857da78ac)
