### ISSUE TITLE
This(500) is not the error code defined in functional document

### ISSUE THREAD

**Issue by Japoivvb** [Xavier-Amatller/exempleProjecte#53]
https://github.com/Xavier-Amatller/exempleProjecte/blob/0a6eb4f8c940e1734e33b06ce71e3d2d25274087/src/Controller/NurseController.php#L55

**Comment by Xavier-Amatller** [comment]
El error 500 lo hemos añadido para comprobar si nos devuelve un error interno del servidor que aloja la base de datos.
