### ISSUE TITLE
Extra access to database after update, only required if nurse object data is going to be returned as response

### ISSUE THREAD

**Issue by Japoivvb** [Xavier-Amatller/exempleProjecte#56]
https://github.com/Xavier-Amatller/exempleProjecte/blob/0a6eb4f8c940e1734e33b06ce71e3d2d25274087/src/Controller/NurseController.php#L212

**Comment by Xavier-Amatller** [comment]
![image](https://github.com/user-attachments/assets/314f347a-4203-422d-ad87-059a6154f0fd)
